TOKEN = ''#Токен бота в ТГ
TOKEN_VK = ''#Токен приложения в вк
TOKEN_VK_USER = ''#Токен Юзера
VK_API = '5.131'
VK_LANG = '0'
sortPhotoVK = '0'
radiusPhotoSearch = '999'
countGEOVk = '150' #Максимум на телеграф 158+-
countCommentVK = '50'
YA_API = ''#Апи яндекса для карт
tgAdminUserName = '@arasaka_2077'
shareBotAdv = 'Не забудь поделиться с друзьми этим ботом🤖\nЗа приглашенного друга дается 5 рублей!\n'
countVkDocs = '50'
QIWI_ACCOUNT = ''#Номер кошелька киви
QIWI_TOKEN = ''#API киви
CHECK_QIWI = 'https://qiwi.com/n/OLDTYT'
TIME_SPAM = 2
SPAM_SMS = 10
TIME_CALLBACK = 5
CALLBACK_REQ = 5
PRICE_FACESEARCH = 20
FACESEARCH_API = ''#FaceSearchAPI
PRICE_SEARCHAUTO = 3